# Generated by Django 4.0.6 on 2022-07-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='post',
            new_name='drop',
        ),
    ]
